[build-system]
requires = ["setuptools>=75.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zzz-simulator"
version = "0.1.0"
description = "A simulator for ZZZ game"
requires-python = ">=3.12"
dependencies = [
    "pandas~=2.2.3",
    "tqdm~=4.66.5",
    "numpy~=2.1.3",
    "dash~=2.18.2",
    "plotly~=6.0.0",
    "setuptools~=75.1.0",
    "streamlit~=1.40.0",
    "toml~=0.10.2"
]

[project.scripts]
zsim = "zsim.run:main"

[tool.setuptools]
packages = ["zsim"]
